swoole.lo: /root/software/php/php5/exts/swoole-2.0.10/swoole.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/software/php/php5/exts/swoole-2.0.10 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/swoole-2.0.10/swoole.c -o swoole.lo 
swoole_server.lo: /root/software/php/php5/exts/swoole-2.0.10/swoole_server.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/software/php/php5/exts/swoole-2.0.10 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/swoole-2.0.10/swoole_server.c -o swoole_server.lo 
swoole_server_port.lo: /root/software/php/php5/exts/swoole-2.0.10/swoole_server_port.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/software/php/php5/exts/swoole-2.0.10 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/swoole-2.0.10/swoole_server_port.c -o swoole_server_port.lo 
swoole_atomic.lo: /root/software/php/php5/exts/swoole-2.0.10/swoole_atomic.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/software/php/php5/exts/swoole-2.0.10 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/swoole-2.0.10/swoole_atomic.c -o swoole_atomic.lo 
swoole_lock.lo: /root/software/php/php5/exts/swoole-2.0.10/swoole_lock.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/software/php/php5/exts/swoole-2.0.10 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/swoole-2.0.10/swoole_lock.c -o swoole_lock.lo 
swoole_client.lo: /root/software/php/php5/exts/swoole-2.0.10/swoole_client.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/software/php/php5/exts/swoole-2.0.10 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/swoole-2.0.10/swoole_client.c -o swoole_client.lo 
swoole_client_coro.lo: /root/software/php/php5/exts/swoole-2.0.10/swoole_client_coro.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/software/php/php5/exts/swoole-2.0.10 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/swoole-2.0.10/swoole_client_coro.c -o swoole_client_coro.lo 
swoole_coroutine.lo: /root/software/php/php5/exts/swoole-2.0.10/swoole_coroutine.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/software/php/php5/exts/swoole-2.0.10 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/swoole-2.0.10/swoole_coroutine.c -o swoole_coroutine.lo 
swoole_coroutine_util.lo: /root/software/php/php5/exts/swoole-2.0.10/swoole_coroutine_util.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/software/php/php5/exts/swoole-2.0.10 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/swoole-2.0.10/swoole_coroutine_util.c -o swoole_coroutine_util.lo 
swoole_event.lo: /root/software/php/php5/exts/swoole-2.0.10/swoole_event.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/software/php/php5/exts/swoole-2.0.10 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/swoole-2.0.10/swoole_event.c -o swoole_event.lo 
swoole_timer.lo: /root/software/php/php5/exts/swoole-2.0.10/swoole_timer.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/software/php/php5/exts/swoole-2.0.10 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/swoole-2.0.10/swoole_timer.c -o swoole_timer.lo 
swoole_async.lo: /root/software/php/php5/exts/swoole-2.0.10/swoole_async.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/software/php/php5/exts/swoole-2.0.10 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/swoole-2.0.10/swoole_async.c -o swoole_async.lo 
swoole_process.lo: /root/software/php/php5/exts/swoole-2.0.10/swoole_process.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/software/php/php5/exts/swoole-2.0.10 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/swoole-2.0.10/swoole_process.c -o swoole_process.lo 
swoole_serialize.lo: /root/software/php/php5/exts/swoole-2.0.10/swoole_serialize.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/software/php/php5/exts/swoole-2.0.10 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/swoole-2.0.10/swoole_serialize.c -o swoole_serialize.lo 
swoole_buffer.lo: /root/software/php/php5/exts/swoole-2.0.10/swoole_buffer.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/software/php/php5/exts/swoole-2.0.10 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/swoole-2.0.10/swoole_buffer.c -o swoole_buffer.lo 
swoole_table.lo: /root/software/php/php5/exts/swoole-2.0.10/swoole_table.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/software/php/php5/exts/swoole-2.0.10 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/swoole-2.0.10/swoole_table.c -o swoole_table.lo 
swoole_http_server.lo: /root/software/php/php5/exts/swoole-2.0.10/swoole_http_server.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/software/php/php5/exts/swoole-2.0.10 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/swoole-2.0.10/swoole_http_server.c -o swoole_http_server.lo 
swoole_http_v2_server.lo: /root/software/php/php5/exts/swoole-2.0.10/swoole_http_v2_server.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/software/php/php5/exts/swoole-2.0.10 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/swoole-2.0.10/swoole_http_v2_server.c -o swoole_http_v2_server.lo 
swoole_http_v2_client.lo: /root/software/php/php5/exts/swoole-2.0.10/swoole_http_v2_client.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/software/php/php5/exts/swoole-2.0.10 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/swoole-2.0.10/swoole_http_v2_client.c -o swoole_http_v2_client.lo 
swoole_websocket_server.lo: /root/software/php/php5/exts/swoole-2.0.10/swoole_websocket_server.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/software/php/php5/exts/swoole-2.0.10 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/swoole-2.0.10/swoole_websocket_server.c -o swoole_websocket_server.lo 
swoole_http_client.lo: /root/software/php/php5/exts/swoole-2.0.10/swoole_http_client.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/software/php/php5/exts/swoole-2.0.10 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/swoole-2.0.10/swoole_http_client.c -o swoole_http_client.lo 
swoole_http_client_coro.lo: /root/software/php/php5/exts/swoole-2.0.10/swoole_http_client_coro.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/software/php/php5/exts/swoole-2.0.10 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/swoole-2.0.10/swoole_http_client_coro.c -o swoole_http_client_coro.lo 
swoole_mysql.lo: /root/software/php/php5/exts/swoole-2.0.10/swoole_mysql.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/software/php/php5/exts/swoole-2.0.10 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/swoole-2.0.10/swoole_mysql.c -o swoole_mysql.lo 
swoole_mysql_coro.lo: /root/software/php/php5/exts/swoole-2.0.10/swoole_mysql_coro.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/software/php/php5/exts/swoole-2.0.10 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/swoole-2.0.10/swoole_mysql_coro.c -o swoole_mysql_coro.lo 
swoole_redis.lo: /root/software/php/php5/exts/swoole-2.0.10/swoole_redis.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/software/php/php5/exts/swoole-2.0.10 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/swoole-2.0.10/swoole_redis.c -o swoole_redis.lo 
swoole_redis_coro.lo: /root/software/php/php5/exts/swoole-2.0.10/swoole_redis_coro.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/software/php/php5/exts/swoole-2.0.10 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/swoole-2.0.10/swoole_redis_coro.c -o swoole_redis_coro.lo 
swoole_redis_server.lo: /root/software/php/php5/exts/swoole-2.0.10/swoole_redis_server.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/software/php/php5/exts/swoole-2.0.10 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/swoole-2.0.10/swoole_redis_server.c -o swoole_redis_server.lo 
swoole_mmap.lo: /root/software/php/php5/exts/swoole-2.0.10/swoole_mmap.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/software/php/php5/exts/swoole-2.0.10 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/swoole-2.0.10/swoole_mmap.c -o swoole_mmap.lo 
swoole_channel.lo: /root/software/php/php5/exts/swoole-2.0.10/swoole_channel.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/software/php/php5/exts/swoole-2.0.10 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/swoole-2.0.10/swoole_channel.c -o swoole_channel.lo 
src/core/base.lo: /root/software/php/php5/exts/swoole-2.0.10/src/core/base.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/software/php/php5/exts/swoole-2.0.10 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/swoole-2.0.10/src/core/base.c -o src/core/base.lo 
src/core/log.lo: /root/software/php/php5/exts/swoole-2.0.10/src/core/log.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/software/php/php5/exts/swoole-2.0.10 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/swoole-2.0.10/src/core/log.c -o src/core/log.lo 
src/core/hashmap.lo: /root/software/php/php5/exts/swoole-2.0.10/src/core/hashmap.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/software/php/php5/exts/swoole-2.0.10 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/swoole-2.0.10/src/core/hashmap.c -o src/core/hashmap.lo 
src/core/RingQueue.lo: /root/software/php/php5/exts/swoole-2.0.10/src/core/RingQueue.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/software/php/php5/exts/swoole-2.0.10 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/swoole-2.0.10/src/core/RingQueue.c -o src/core/RingQueue.lo 
src/core/Channel.lo: /root/software/php/php5/exts/swoole-2.0.10/src/core/Channel.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/software/php/php5/exts/swoole-2.0.10 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/swoole-2.0.10/src/core/Channel.c -o src/core/Channel.lo 
src/core/string.lo: /root/software/php/php5/exts/swoole-2.0.10/src/core/string.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/software/php/php5/exts/swoole-2.0.10 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/swoole-2.0.10/src/core/string.c -o src/core/string.lo 
src/core/array.lo: /root/software/php/php5/exts/swoole-2.0.10/src/core/array.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/software/php/php5/exts/swoole-2.0.10 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/swoole-2.0.10/src/core/array.c -o src/core/array.lo 
src/core/socket.lo: /root/software/php/php5/exts/swoole-2.0.10/src/core/socket.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/software/php/php5/exts/swoole-2.0.10 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/swoole-2.0.10/src/core/socket.c -o src/core/socket.lo 
src/core/list.lo: /root/software/php/php5/exts/swoole-2.0.10/src/core/list.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/software/php/php5/exts/swoole-2.0.10 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/swoole-2.0.10/src/core/list.c -o src/core/list.lo 
src/core/heap.lo: /root/software/php/php5/exts/swoole-2.0.10/src/core/heap.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/software/php/php5/exts/swoole-2.0.10 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/swoole-2.0.10/src/core/heap.c -o src/core/heap.lo 
src/memory/ShareMemory.lo: /root/software/php/php5/exts/swoole-2.0.10/src/memory/ShareMemory.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/software/php/php5/exts/swoole-2.0.10 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/swoole-2.0.10/src/memory/ShareMemory.c -o src/memory/ShareMemory.lo 
src/memory/MemoryGlobal.lo: /root/software/php/php5/exts/swoole-2.0.10/src/memory/MemoryGlobal.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/software/php/php5/exts/swoole-2.0.10 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/swoole-2.0.10/src/memory/MemoryGlobal.c -o src/memory/MemoryGlobal.lo 
src/memory/RingBuffer.lo: /root/software/php/php5/exts/swoole-2.0.10/src/memory/RingBuffer.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/software/php/php5/exts/swoole-2.0.10 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/swoole-2.0.10/src/memory/RingBuffer.c -o src/memory/RingBuffer.lo 
src/memory/FixedPool.lo: /root/software/php/php5/exts/swoole-2.0.10/src/memory/FixedPool.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/software/php/php5/exts/swoole-2.0.10 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/swoole-2.0.10/src/memory/FixedPool.c -o src/memory/FixedPool.lo 
src/memory/Malloc.lo: /root/software/php/php5/exts/swoole-2.0.10/src/memory/Malloc.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/software/php/php5/exts/swoole-2.0.10 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/swoole-2.0.10/src/memory/Malloc.c -o src/memory/Malloc.lo 
src/memory/Table.lo: /root/software/php/php5/exts/swoole-2.0.10/src/memory/Table.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/software/php/php5/exts/swoole-2.0.10 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/swoole-2.0.10/src/memory/Table.c -o src/memory/Table.lo 
src/memory/Buffer.lo: /root/software/php/php5/exts/swoole-2.0.10/src/memory/Buffer.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/software/php/php5/exts/swoole-2.0.10 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/swoole-2.0.10/src/memory/Buffer.c -o src/memory/Buffer.lo 
src/factory/Factory.lo: /root/software/php/php5/exts/swoole-2.0.10/src/factory/Factory.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/software/php/php5/exts/swoole-2.0.10 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/swoole-2.0.10/src/factory/Factory.c -o src/factory/Factory.lo 
src/factory/FactoryThread.lo: /root/software/php/php5/exts/swoole-2.0.10/src/factory/FactoryThread.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/software/php/php5/exts/swoole-2.0.10 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/swoole-2.0.10/src/factory/FactoryThread.c -o src/factory/FactoryThread.lo 
src/factory/FactoryProcess.lo: /root/software/php/php5/exts/swoole-2.0.10/src/factory/FactoryProcess.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/software/php/php5/exts/swoole-2.0.10 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/swoole-2.0.10/src/factory/FactoryProcess.c -o src/factory/FactoryProcess.lo 
src/reactor/ReactorBase.lo: /root/software/php/php5/exts/swoole-2.0.10/src/reactor/ReactorBase.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/software/php/php5/exts/swoole-2.0.10 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/swoole-2.0.10/src/reactor/ReactorBase.c -o src/reactor/ReactorBase.lo 
src/reactor/ReactorSelect.lo: /root/software/php/php5/exts/swoole-2.0.10/src/reactor/ReactorSelect.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/software/php/php5/exts/swoole-2.0.10 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/swoole-2.0.10/src/reactor/ReactorSelect.c -o src/reactor/ReactorSelect.lo 
src/reactor/ReactorPoll.lo: /root/software/php/php5/exts/swoole-2.0.10/src/reactor/ReactorPoll.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/software/php/php5/exts/swoole-2.0.10 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/swoole-2.0.10/src/reactor/ReactorPoll.c -o src/reactor/ReactorPoll.lo 
src/reactor/ReactorEpoll.lo: /root/software/php/php5/exts/swoole-2.0.10/src/reactor/ReactorEpoll.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/software/php/php5/exts/swoole-2.0.10 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/swoole-2.0.10/src/reactor/ReactorEpoll.c -o src/reactor/ReactorEpoll.lo 
src/reactor/ReactorKqueue.lo: /root/software/php/php5/exts/swoole-2.0.10/src/reactor/ReactorKqueue.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/software/php/php5/exts/swoole-2.0.10 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/swoole-2.0.10/src/reactor/ReactorKqueue.c -o src/reactor/ReactorKqueue.lo 
src/pipe/PipeBase.lo: /root/software/php/php5/exts/swoole-2.0.10/src/pipe/PipeBase.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/software/php/php5/exts/swoole-2.0.10 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/swoole-2.0.10/src/pipe/PipeBase.c -o src/pipe/PipeBase.lo 
src/pipe/PipeEventfd.lo: /root/software/php/php5/exts/swoole-2.0.10/src/pipe/PipeEventfd.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/software/php/php5/exts/swoole-2.0.10 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/swoole-2.0.10/src/pipe/PipeEventfd.c -o src/pipe/PipeEventfd.lo 
src/pipe/PipeUnsock.lo: /root/software/php/php5/exts/swoole-2.0.10/src/pipe/PipeUnsock.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/software/php/php5/exts/swoole-2.0.10 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/swoole-2.0.10/src/pipe/PipeUnsock.c -o src/pipe/PipeUnsock.lo 
src/lock/Semaphore.lo: /root/software/php/php5/exts/swoole-2.0.10/src/lock/Semaphore.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/software/php/php5/exts/swoole-2.0.10 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/swoole-2.0.10/src/lock/Semaphore.c -o src/lock/Semaphore.lo 
src/lock/Mutex.lo: /root/software/php/php5/exts/swoole-2.0.10/src/lock/Mutex.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/software/php/php5/exts/swoole-2.0.10 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/swoole-2.0.10/src/lock/Mutex.c -o src/lock/Mutex.lo 
src/lock/RWLock.lo: /root/software/php/php5/exts/swoole-2.0.10/src/lock/RWLock.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/software/php/php5/exts/swoole-2.0.10 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/swoole-2.0.10/src/lock/RWLock.c -o src/lock/RWLock.lo 
src/lock/SpinLock.lo: /root/software/php/php5/exts/swoole-2.0.10/src/lock/SpinLock.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/software/php/php5/exts/swoole-2.0.10 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/swoole-2.0.10/src/lock/SpinLock.c -o src/lock/SpinLock.lo 
src/lock/FileLock.lo: /root/software/php/php5/exts/swoole-2.0.10/src/lock/FileLock.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/software/php/php5/exts/swoole-2.0.10 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/swoole-2.0.10/src/lock/FileLock.c -o src/lock/FileLock.lo 
src/lock/Cond.lo: /root/software/php/php5/exts/swoole-2.0.10/src/lock/Cond.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/software/php/php5/exts/swoole-2.0.10 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/swoole-2.0.10/src/lock/Cond.c -o src/lock/Cond.lo 
src/network/Server.lo: /root/software/php/php5/exts/swoole-2.0.10/src/network/Server.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/software/php/php5/exts/swoole-2.0.10 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/swoole-2.0.10/src/network/Server.c -o src/network/Server.lo 
src/network/TaskWorker.lo: /root/software/php/php5/exts/swoole-2.0.10/src/network/TaskWorker.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/software/php/php5/exts/swoole-2.0.10 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/swoole-2.0.10/src/network/TaskWorker.c -o src/network/TaskWorker.lo 
src/network/Client.lo: /root/software/php/php5/exts/swoole-2.0.10/src/network/Client.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/software/php/php5/exts/swoole-2.0.10 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/swoole-2.0.10/src/network/Client.c -o src/network/Client.lo 
src/network/Connection.lo: /root/software/php/php5/exts/swoole-2.0.10/src/network/Connection.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/software/php/php5/exts/swoole-2.0.10 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/swoole-2.0.10/src/network/Connection.c -o src/network/Connection.lo 
src/network/ProcessPool.lo: /root/software/php/php5/exts/swoole-2.0.10/src/network/ProcessPool.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/software/php/php5/exts/swoole-2.0.10 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/swoole-2.0.10/src/network/ProcessPool.c -o src/network/ProcessPool.lo 
src/network/ThreadPool.lo: /root/software/php/php5/exts/swoole-2.0.10/src/network/ThreadPool.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/software/php/php5/exts/swoole-2.0.10 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/swoole-2.0.10/src/network/ThreadPool.c -o src/network/ThreadPool.lo 
src/network/ReactorThread.lo: /root/software/php/php5/exts/swoole-2.0.10/src/network/ReactorThread.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/software/php/php5/exts/swoole-2.0.10 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/swoole-2.0.10/src/network/ReactorThread.c -o src/network/ReactorThread.lo 
src/network/ReactorProcess.lo: /root/software/php/php5/exts/swoole-2.0.10/src/network/ReactorProcess.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/software/php/php5/exts/swoole-2.0.10 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/swoole-2.0.10/src/network/ReactorProcess.c -o src/network/ReactorProcess.lo 
src/network/Manager.lo: /root/software/php/php5/exts/swoole-2.0.10/src/network/Manager.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/software/php/php5/exts/swoole-2.0.10 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/swoole-2.0.10/src/network/Manager.c -o src/network/Manager.lo 
src/network/Worker.lo: /root/software/php/php5/exts/swoole-2.0.10/src/network/Worker.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/software/php/php5/exts/swoole-2.0.10 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/swoole-2.0.10/src/network/Worker.c -o src/network/Worker.lo 
src/network/Timer.lo: /root/software/php/php5/exts/swoole-2.0.10/src/network/Timer.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/software/php/php5/exts/swoole-2.0.10 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/swoole-2.0.10/src/network/Timer.c -o src/network/Timer.lo 
src/network/Port.lo: /root/software/php/php5/exts/swoole-2.0.10/src/network/Port.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/software/php/php5/exts/swoole-2.0.10 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/swoole-2.0.10/src/network/Port.c -o src/network/Port.lo 
src/network/DNS.lo: /root/software/php/php5/exts/swoole-2.0.10/src/network/DNS.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/software/php/php5/exts/swoole-2.0.10 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/swoole-2.0.10/src/network/DNS.c -o src/network/DNS.lo 
src/network/TimeWheel.lo: /root/software/php/php5/exts/swoole-2.0.10/src/network/TimeWheel.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/software/php/php5/exts/swoole-2.0.10 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/swoole-2.0.10/src/network/TimeWheel.c -o src/network/TimeWheel.lo 
src/os/base.lo: /root/software/php/php5/exts/swoole-2.0.10/src/os/base.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/software/php/php5/exts/swoole-2.0.10 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/swoole-2.0.10/src/os/base.c -o src/os/base.lo 
src/os/linux_aio.lo: /root/software/php/php5/exts/swoole-2.0.10/src/os/linux_aio.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/software/php/php5/exts/swoole-2.0.10 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/swoole-2.0.10/src/os/linux_aio.c -o src/os/linux_aio.lo 
src/os/msg_queue.lo: /root/software/php/php5/exts/swoole-2.0.10/src/os/msg_queue.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/software/php/php5/exts/swoole-2.0.10 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/swoole-2.0.10/src/os/msg_queue.c -o src/os/msg_queue.lo 
src/os/sendfile.lo: /root/software/php/php5/exts/swoole-2.0.10/src/os/sendfile.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/software/php/php5/exts/swoole-2.0.10 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/swoole-2.0.10/src/os/sendfile.c -o src/os/sendfile.lo 
src/os/signal.lo: /root/software/php/php5/exts/swoole-2.0.10/src/os/signal.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/software/php/php5/exts/swoole-2.0.10 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/swoole-2.0.10/src/os/signal.c -o src/os/signal.lo 
src/os/timer.lo: /root/software/php/php5/exts/swoole-2.0.10/src/os/timer.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/software/php/php5/exts/swoole-2.0.10 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/swoole-2.0.10/src/os/timer.c -o src/os/timer.lo 
src/protocol/Base.lo: /root/software/php/php5/exts/swoole-2.0.10/src/protocol/Base.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/software/php/php5/exts/swoole-2.0.10 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/swoole-2.0.10/src/protocol/Base.c -o src/protocol/Base.lo 
src/protocol/SSL.lo: /root/software/php/php5/exts/swoole-2.0.10/src/protocol/SSL.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/software/php/php5/exts/swoole-2.0.10 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/swoole-2.0.10/src/protocol/SSL.c -o src/protocol/SSL.lo 
src/protocol/Http.lo: /root/software/php/php5/exts/swoole-2.0.10/src/protocol/Http.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/software/php/php5/exts/swoole-2.0.10 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/swoole-2.0.10/src/protocol/Http.c -o src/protocol/Http.lo 
src/protocol/Http2.lo: /root/software/php/php5/exts/swoole-2.0.10/src/protocol/Http2.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/software/php/php5/exts/swoole-2.0.10 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/swoole-2.0.10/src/protocol/Http2.c -o src/protocol/Http2.lo 
src/protocol/WebSocket.lo: /root/software/php/php5/exts/swoole-2.0.10/src/protocol/WebSocket.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/software/php/php5/exts/swoole-2.0.10 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/swoole-2.0.10/src/protocol/WebSocket.c -o src/protocol/WebSocket.lo 
src/protocol/Mqtt.lo: /root/software/php/php5/exts/swoole-2.0.10/src/protocol/Mqtt.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/software/php/php5/exts/swoole-2.0.10 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/swoole-2.0.10/src/protocol/Mqtt.c -o src/protocol/Mqtt.lo 
src/protocol/Socks5.lo: /root/software/php/php5/exts/swoole-2.0.10/src/protocol/Socks5.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/software/php/php5/exts/swoole-2.0.10 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/swoole-2.0.10/src/protocol/Socks5.c -o src/protocol/Socks5.lo 
src/protocol/MimeTypes.lo: /root/software/php/php5/exts/swoole-2.0.10/src/protocol/MimeTypes.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/software/php/php5/exts/swoole-2.0.10 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/swoole-2.0.10/src/protocol/MimeTypes.c -o src/protocol/MimeTypes.lo 
src/protocol/Redis.lo: /root/software/php/php5/exts/swoole-2.0.10/src/protocol/Redis.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/software/php/php5/exts/swoole-2.0.10 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/swoole-2.0.10/src/protocol/Redis.c -o src/protocol/Redis.lo 
src/protocol/Base64.lo: /root/software/php/php5/exts/swoole-2.0.10/src/protocol/Base64.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/software/php/php5/exts/swoole-2.0.10 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/swoole-2.0.10/src/protocol/Base64.c -o src/protocol/Base64.lo 
thirdparty/php_http_parser.lo: /root/software/php/php5/exts/swoole-2.0.10/thirdparty/php_http_parser.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/software/php/php5/exts/swoole-2.0.10 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/swoole-2.0.10/thirdparty/php_http_parser.c -o thirdparty/php_http_parser.lo 
thirdparty/multipart_parser.lo: /root/software/php/php5/exts/swoole-2.0.10/thirdparty/multipart_parser.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/software/php/php5/exts/swoole-2.0.10 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/swoole-2.0.10/thirdparty/multipart_parser.c -o thirdparty/multipart_parser.lo 
$(phplibdir)/swoole.la: ./swoole.la
	$(LIBTOOL) --mode=install cp ./swoole.la $(phplibdir)

./swoole.la: $(shared_objects_swoole) $(SWOOLE_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_swoole) $(SWOOLE_SHARED_LIBADD)

