php5/php_event.lo: /root/software/php/php5/exts/event-2.4.1/php5/php_event.c
	$(LIBTOOL) --mode=compile $(CC) -g -O2 -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/root/software/php/php5/exts/event-2.4.1 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/event-2.4.1/php5/php_event.c -o php5/php_event.lo 
php5/src/util.lo: /root/software/php/php5/exts/event-2.4.1/php5/src/util.c
	$(LIBTOOL) --mode=compile $(CC) -g -O2 -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/root/software/php/php5/exts/event-2.4.1 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/event-2.4.1/php5/src/util.c -o php5/src/util.lo 
php5/src/fe.lo: /root/software/php/php5/exts/event-2.4.1/php5/src/fe.c
	$(LIBTOOL) --mode=compile $(CC) -g -O2 -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/root/software/php/php5/exts/event-2.4.1 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/event-2.4.1/php5/src/fe.c -o php5/src/fe.lo 
php5/src/pe.lo: /root/software/php/php5/exts/event-2.4.1/php5/src/pe.c
	$(LIBTOOL) --mode=compile $(CC) -g -O2 -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/root/software/php/php5/exts/event-2.4.1 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/event-2.4.1/php5/src/pe.c -o php5/src/pe.lo 
php5/classes/event.lo: /root/software/php/php5/exts/event-2.4.1/php5/classes/event.c
	$(LIBTOOL) --mode=compile $(CC) -g -O2 -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/root/software/php/php5/exts/event-2.4.1 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/event-2.4.1/php5/classes/event.c -o php5/classes/event.lo 
php5/classes/base.lo: /root/software/php/php5/exts/event-2.4.1/php5/classes/base.c
	$(LIBTOOL) --mode=compile $(CC) -g -O2 -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/root/software/php/php5/exts/event-2.4.1 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/event-2.4.1/php5/classes/base.c -o php5/classes/base.lo 
php5/classes/event_config.lo: /root/software/php/php5/exts/event-2.4.1/php5/classes/event_config.c
	$(LIBTOOL) --mode=compile $(CC) -g -O2 -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/root/software/php/php5/exts/event-2.4.1 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/event-2.4.1/php5/classes/event_config.c -o php5/classes/event_config.lo 
php5/classes/buffer_event.lo: /root/software/php/php5/exts/event-2.4.1/php5/classes/buffer_event.c
	$(LIBTOOL) --mode=compile $(CC) -g -O2 -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/root/software/php/php5/exts/event-2.4.1 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/event-2.4.1/php5/classes/buffer_event.c -o php5/classes/buffer_event.lo 
php5/classes/buffer.lo: /root/software/php/php5/exts/event-2.4.1/php5/classes/buffer.c
	$(LIBTOOL) --mode=compile $(CC) -g -O2 -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/root/software/php/php5/exts/event-2.4.1 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/event-2.4.1/php5/classes/buffer.c -o php5/classes/buffer.lo 
php5/classes/event_util.lo: /root/software/php/php5/exts/event-2.4.1/php5/classes/event_util.c
	$(LIBTOOL) --mode=compile $(CC) -g -O2 -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/root/software/php/php5/exts/event-2.4.1 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/event-2.4.1/php5/classes/event_util.c -o php5/classes/event_util.lo 
php5/classes/dns.lo: /root/software/php/php5/exts/event-2.4.1/php5/classes/dns.c
	$(LIBTOOL) --mode=compile $(CC) -g -O2 -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/root/software/php/php5/exts/event-2.4.1 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/event-2.4.1/php5/classes/dns.c -o php5/classes/dns.lo 
php5/classes/listener.lo: /root/software/php/php5/exts/event-2.4.1/php5/classes/listener.c
	$(LIBTOOL) --mode=compile $(CC) -g -O2 -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/root/software/php/php5/exts/event-2.4.1 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/event-2.4.1/php5/classes/listener.c -o php5/classes/listener.lo 
php5/classes/http.lo: /root/software/php/php5/exts/event-2.4.1/php5/classes/http.c
	$(LIBTOOL) --mode=compile $(CC) -g -O2 -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/root/software/php/php5/exts/event-2.4.1 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/event-2.4.1/php5/classes/http.c -o php5/classes/http.lo 
php5/classes/http_request.lo: /root/software/php/php5/exts/event-2.4.1/php5/classes/http_request.c
	$(LIBTOOL) --mode=compile $(CC) -g -O2 -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/root/software/php/php5/exts/event-2.4.1 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/event-2.4.1/php5/classes/http_request.c -o php5/classes/http_request.lo 
php5/classes/http_connection.lo: /root/software/php/php5/exts/event-2.4.1/php5/classes/http_connection.c
	$(LIBTOOL) --mode=compile $(CC) -g -O2 -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/root/software/php/php5/exts/event-2.4.1 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/event-2.4.1/php5/classes/http_connection.c -o php5/classes/http_connection.lo 
php5/classes/ssl_context.lo: /root/software/php/php5/exts/event-2.4.1/php5/classes/ssl_context.c
	$(LIBTOOL) --mode=compile $(CC) -g -O2 -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/root/software/php/php5/exts/event-2.4.1 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/event-2.4.1/php5/classes/ssl_context.c -o php5/classes/ssl_context.lo 
$(phplibdir)/event.la: ./event.la
	$(LIBTOOL) --mode=install cp ./event.la $(phplibdir)

./event.la: $(shared_objects_event) $(EVENT_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_event) $(EVENT_SHARED_LIBADD)

