redis.lo: /root/software/php/php5/exts/redis-4.1.1/redis.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/software/php/php5/exts/redis-4.1.1 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/redis-4.1.1/redis.c -o redis.lo 
redis_commands.lo: /root/software/php/php5/exts/redis-4.1.1/redis_commands.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/software/php/php5/exts/redis-4.1.1 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/redis-4.1.1/redis_commands.c -o redis_commands.lo 
library.lo: /root/software/php/php5/exts/redis-4.1.1/library.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/software/php/php5/exts/redis-4.1.1 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/redis-4.1.1/library.c -o library.lo 
redis_session.lo: /root/software/php/php5/exts/redis-4.1.1/redis_session.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/software/php/php5/exts/redis-4.1.1 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/redis-4.1.1/redis_session.c -o redis_session.lo 
redis_array.lo: /root/software/php/php5/exts/redis-4.1.1/redis_array.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/software/php/php5/exts/redis-4.1.1 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/redis-4.1.1/redis_array.c -o redis_array.lo 
redis_array_impl.lo: /root/software/php/php5/exts/redis-4.1.1/redis_array_impl.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/software/php/php5/exts/redis-4.1.1 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/redis-4.1.1/redis_array_impl.c -o redis_array_impl.lo 
redis_cluster.lo: /root/software/php/php5/exts/redis-4.1.1/redis_cluster.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/software/php/php5/exts/redis-4.1.1 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/redis-4.1.1/redis_cluster.c -o redis_cluster.lo 
cluster_library.lo: /root/software/php/php5/exts/redis-4.1.1/cluster_library.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/software/php/php5/exts/redis-4.1.1 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/software/php/php5/exts/redis-4.1.1/cluster_library.c -o cluster_library.lo 
$(phplibdir)/redis.la: ./redis.la
	$(LIBTOOL) --mode=install cp ./redis.la $(phplibdir)

./redis.la: $(shared_objects_redis) $(REDIS_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_redis) $(REDIS_SHARED_LIBADD)

